# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(size=(7, 7))
print(random_tensor)
print(f"텐서의 모양: {random_tensor.shape}")

tensor([[0.5257, 0.6951, 0.4332, 0.2222, 0.4999, 0.7380, 0.7623],
        [0.8093, 0.4177, 0.3612, 0.1533, 0.8277, 0.7481, 0.6107],
        [0.5736, 0.6596, 0.3625, 0.5925, 0.6454, 0.4119, 0.2772],
        [0.7599, 0.5221, 0.7627, 0.8637, 0.1834, 0.3644, 0.3611],
        [0.6786, 0.3641, 0.0302, 0.3968, 0.8467, 0.0112, 0.7651],
        [0.7665, 0.2597, 0.7224, 0.0064, 0.7995, 0.7815, 0.8583],
        [0.1438, 0.0169, 0.9603, 0.1777, 0.7554, 0.9260, 0.2198]])
텐서의 모양: torch.Size([7, 7])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
tensor_B = torch.rand(size=(1, 7))
# Perform matrix multiplication
output = torch.matmul(random_tensor, tensor_B.T)
print(f"Output shape: {output.shape}")
print(f"\n결과 값:\n{output}")

Output shape: torch.Size([7, 1])

결과 값:
tensor([[1.3067],
        [1.2262],
        [1.4792],
        [1.3364],
        [1.3055],
        [1.0653],
        [0.8363]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

# Create two random tensors
tensor_A = torch.rand(7, 7)
torch.manual_seed(RANDOM_SEED)
tensor_B = torch.rand(1, 7)

# Matrix multiply tensors
output = torch.matmul(tensor_A, tensor_B.T)
print(output, output.shape)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
RANDOM_SEED = 1234
torch.manual_seed(RANDOM_SEED)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2, 3)).to(device)
torch.manual_seed(RANDOM_SEED)
tensor_B = torch.rand(size=(2, 3)).to(device)

print(tensor_A, tensor_A.device)
print(tensor_B, tensor_B.device)

Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') cuda:0
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') cuda:0



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
device = "cuda" if torch.cuda.is_available() else "cpu"

torch.manual_seed(1234)
tensor_A = torch.rand(size=(2, 3)).to(device)

torch.manual_seed(1234)
tensor_B = torch.rand(size=(2, 3)).to(device)

output = torch.matmul(tensor_A, tensor_B.T)

print(output)
print(f"결과 텐서의 모양: {output.shape}")
print(f"연산이 수행된 장치: {output.device}")

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')
결과 텐서의 모양: torch.Size([2, 2])
연산이 수행된 장치: cuda:0


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
max_val = torch.max(output)

# Find min
min_val = torch.min(output)

print(f"최댓값: {max_val}")
print(f"최솟값: {min_val}")

최댓값: 0.628727912902832
최솟값: 0.21611443161964417


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
max_index = torch.argmax(output)

# Find arg min
min_index = torch.argmin(output)

print(f"최댓값 위치(인덱스): {max_index.item()}")
print(f"최솟값 위치(인덱스): {min_index.item()}")

최댓값 위치(인덱스): 3
최솟값 위치(인덱스): 1



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_original = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_squeezed = tensor_original.squeeze()

# Print out tensors and their shapes
print(f"첫 번째 텐서: {tensor_original}")
print(f"첫 번째 텐서 모양: {tensor_original.shape}\n")

print(f"두 번째 텐서 (Squeezed): {tensor_squeezed}")
print(f"두 번째 텐서 모양: {tensor_squeezed.shape}")

첫 번째 텐서: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
첫 번째 텐서 모양: torch.Size([1, 1, 1, 10])

두 번째 텐서 (Squeezed): tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
두 번째 텐서 모양: torch.Size([10])
