In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


#1-1. 머신러닝의 개념
1. 머신러닝
: 애플리케이션을 수정하지 않고도 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법
* 머신러닝 알고리즘: 데이터를 기반으로 통계적인 신뢰도를 강화하고 예측 오류를 최소화하기 위한 다양한 수학적 기법을 적용해 데이터 내의 패턴을 스스로 인지하고, 신뢰도 있는 예측 결과 도출
# 2. 머신러닝의 분류
* 지도학습
  + 분류
  + 회귀
  + 추천 시스템
  + 시각/음성 감지/인지
  + 텍스트 분석, NLP
* 비지도학습
  + 클러스터링
  + 차원축소
  + 강화학습
#3. 머신러닝의 단점
: 데이터에 매우 의존적
*  좋은 품질의 데이터를 갖추지 못하면 머신러닝의 수행결과도 좋지 않음
* 데이터를 이해하고 효율적으로 가공, 처리, 추출해 최적의 데이터를 기반으로 알고리즘을 구동할 수 있도록 준비하는 능력 중요
#4. 파이썬과 R기반의 머신러닝 비교
: 머신러닝 프로그램을 작성할 수 있는 대표적인 오픈 소스 프로그램 언어들
* R
  + 통계전용 프로그램 언어
  + 전통적인 통계 및 마이닝 패키지의 고비용 문제를 개선하기 위해 만듦
  + 오랜 기간 동안 많은 R 사용자들이 생성하고 검증해온 다양하고 많은 통계 패키지 보유
* 파이썬
  + 다양한 영역에서 사용되는 개발 전문 프로그램 언어
  + 강점: 직관적인 문법, 객체지향과 함수형 프로그래밍 모두를 포괄하는 유연한 프로드램 아키텍처, 다양한 라이브러리
    -  높은 생산성으로 인해 활용도가 매우 높음
    -  오픈 소스 계열의 전폭적인 지원을 받고 있으며 많은 라이브러리로 인해 개발 시 높은 생산성 보장
    -  인터프리터 언어 특성상 속도는 느리지만, 뛰어난 확장성, 유연성, 호환성으로 다양한 영역에서 사용
    - 머신러닝 애플리케이션과 결합한 다양한 애플리케이션 개발 가능
    - 다양한 기업 환경으로의 확산 가능
  + 딥러닝 프레임워크는 파이썬을 중심으로 발전될 가능성이 큼


#1-2 파이썬 머신러닝 생태계를 구성하는 주요 패키지
* 머신러닝 패키지: 사이킷런
* 행렬/선형대수/통계 패키지
  + 넘파이: 행렬과 선형대수를 다룸
  + 사이파이:자연과학과 통계를 위함
* 데이터 핸들링
  + 판다스
    - 2차원 데이터 처리에 특화
    - 넘파이보다 훨씬 편리하게 데이터 처리를 할 수 있는 많은 기능 제공
    - 맷플롯립을 호출해 쥡게 시각화 기능을 지원
* 시각화
  + 맷플롯립
    - 너무 세분화된 API로 익히기 번거로움
    - 디자인 부분에서 투박
    - 데이터 분석가/과학자가 작성하는 코드가 길어지기 때문에 효율이 떨어지고 불편함이 늘어남
  + 시본
    - 맷플롯립을 기반으로 하지만, 보완하기 위한 시각화 패키지
    - 판다스와의 쉬운 연동
    - 더 함축적인 API
    - 분석을 위한 다양한 유형의 그래프/차트 제공
* 아이파이썬: 대화형 파이썬 툴, 전체 프로그램에서 특정 코드 영역별로 개별 수행을 지원하므로 영역별로 코드 이해가 매우 명확하게 설명 가능
  + 주피터 노트북: 대표적 아이파이썬 지원 툴
    - 중요 코드 단위로 설명을 적고 코드를 수행해 그 결과를 볼 수 있음
    - 직관적으로 어떤 코드가 어떤 역할을 하는지 매우 쉽세 이해할 수 있도록 지원




# 1-3 넘파이
: 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지
  + 빠른 배열 연산 속도 보장: 루프를 사용하지 않고 대량 데이터의 배열 연산을 가능하게 함
  + C/C++ 같은 저수준 언어 기반의 호환 API 제
  + 매우 빠른 배열 연산을 보장하지만, 파이썬 언어 자체가 가지는 수행 성능의 제약이 있으므로 수행 성증이 중요한 부분은 C/C++ 기반의 코드로 작성하고, 이를 넘파이에서 호출하는 방식으로 통합함 (ex. 텐서플로)
  + 다양한 데이터 핸들링 기능 제공하지만, 편의성과 다양한 API 지원 측면에서는 아쉬움
#1. 넘파이 ndarray 개요
  + ndarray: 넘파이 기반 데이터 타입, 다차원 배열을 쉽게 생성하고 다양한 연산 수행


In [ ]:
import numpy as np

  * array() 함수: 파이썬의 리스트와 같은 다양한 인자를 입력받아서 ndarray로 변환함
    + 생성된 ndarray 배열의 shape 변수는 ndarray의 크기(행과 열의 수)를 튜플 형태로 가지고 있으며, 이를 통해 ndarray 배열의 차원까지 알 수 있음

  * np.array(): ndarry로 변환을 원하는 객체를 인자로 입력하면 ndarray를 반환함
  * ndarray.shape: ndarray의 차원과 크기를 튜플 형태로 나타내줌
    + array1 [1,2,3]의 shape은 (3,): 1차원 array, 3개의 데이터
    + array2 [[1,2,3],[2,3,4]]의 shape은 (2,3): 2차원 array, 2개의 로우와 3개의 칼럼으로 구성된 2*3=6개의 데이터
    + array3 [[1,2,3]]의 shape은 (1,3): 2차원 array, 1개의 로우와 3개의 칼럼으로 구성된 3개의 데이터
  

In [ ]:
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)
array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)
array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


* ndarray.ndim: 각 array의 차원을 나타내줌
  + array()함수의 인자로는 파이썬 리스트 객체([])가 주로 사용됨: 리스트 []는 1차원이고, 리스트 [[]]는 2차원과 같은 형태로 배열의 차원과 크기를 쉽게 표현할 수 있기 때문
  + {}속 숫자 0은 첫번째 값, 숫자 1은 두번째 값, 숫자 2는 세번째 값을 의미함

In [ ]:
print('array1:{0}차원,array2:{1}차원,array3:{2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1:1차원,array2:2차원,array3:2차원


#2. ndarray의 데이터 타입
* 숫자 값, 문자열 값, 불 값 등이 모두 가능
  + 숫자형: int형(8bit, 16bit, 32bit), unsigned bit형(8bit, 16bit, 32bit),float형(16bit, 32bit, 64bit, 128bit), complex 타입
* 그 연산의 특성상 같은 데이터 타입만 가능 (한 개의 ndarray 객체에 int와 float이 함께 있을 수 X)
* dtype 속성으로 ndarray내의 데이터 타입 확인 가능
  + 리스트형 자료인 list1은 integer숫자인 1,2,3을 값으로 가지고 있음
  + 이를 ndarray로 변경한 ndarray내의 데이터값은 모두 int64형임


In [ ]:
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1,array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


* 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용함
  + int형과 문자열이 섞여 있는 list2를 ndarry로 변환한 array2는 숫자형 값 1,2가 모두 문자열 값인 '1', '2'로 변환됨
  + int형과 float형이 섞여 있는 list3도 int 1,2 모두 1. 2.인 float64형으로 변환됨

In [ ]:
list2=[1,2,'test']
array2=np.array(list2)
print(array2, array2.dtype)

list3=[1,2,3.0]
array3=np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


* astype(): ndatty 내 데이터값의 타입을 변경해줌
  + astype()에 인자로 원하는 타입을 문자열로 지정
  + 대용량 데이터의 nadarry를 만들 때 많은 메모리가 사용되는데, 이를 절약해야 할 때 이용
  + float을 int형으로 변경할 때 소수점 이하는 당연히 모두 없어짐

In [ ]:
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float,array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1=np.array([1.1,2.1,3.1])
array_int2=array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


# 3. ndarray를 편리하게 생성하기 - arange, zeros, ones: 테스트용으로 데이터를 만들거나 대규모의 데이터를 일괄적으로 초기화해야할 때 사용
* arrange(): array를 range()로 표현, 0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터값으로 변환
  + default 함수 인자는 stop값임
  + start값도 부여해 0이 아닌 다른 값부터 시작한 연속 값을 부여할 수도 있음
  + 0부터 stop값인 10에서 -1을 더한 9까지의 연속 숫자 값으로 구성된 1차원 ndarray를 만들어줌




In [ ]:
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


* zeros(): 함수 인자로 튜플 형태의 shape값을 입력하면 모든 값을 0으로 채운 해당 shape을 가진 ndarray를 반환
* ones(): 함수 인자로 튜플 형태의 shape값을 입력하면 모든 값을 1으로 채운 해당 shape을 가진 ndarray를 반환
* 함수 인자로 dtype을 정해주지 않으면 default로 float64형의 데이터로 ndarray를 채움

In [ ]:
zero_array=np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype,zero_array.shape)

one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype,one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


#4. ndarray의 차원과 크기를 변경하는 reshape(): ndarray를 특정 차원 및 크기로 변환
* 변환을 원하는 크기를 함수 인자로 부여
  + 0~9까지의 1차원 ndarray를 2로우X5칼럼, 5로우X2칼럼 형태로 2차원 ndarray로 변환해줌

In [ ]:
array1=np.arange(10)
print('array1:\n',array1)

array2=array1.reshape(2,5)
print('array2:\n',array2)

array3=array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


* 지정된 사이즈로 변경이 불가능하면 오류 발생
  + (10,) 데이터를 (4,3) shape 형태로 변경할 수 없음

In [ ]:
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

* 인자로 -1을 적용하는 경우: 원래 ndarray와 호환되는 새로운 shape로 변환
  + arrray2: array1과 호환될 수 있는 2차원 ndarray로 변환하되, 고정된 5개의 칼럼에 맞는 로우를 자동으로 새롭게 생성해 변환
  + arrray3: array1과 호환될 수 있는 2차원 ndarray로 변환하되, 고정된 5개의 로우에 맞는 칼럼을 자동으로 새롭게 생성해 변환

In [ ]:
array1=np.arange(10)
print(array1)
array2=array1.reshape(-1,5)
print('array2 shape:', array2.shape)
array3=array1.reshape(5,-1)
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


  * 데이터와 호환될 수 없는 형태는 변환할 수 없음
    + array4: 10개의 1차원 데이터를 고정도니 4개의 칼럼을 가진 로우로는 변경할 수 없음

In [ ]:
array1=np.arange(10)
array4=array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

* reshape(-1,1)
  + 원본 ndarray가 어떤 형태이더라도 2차원이고, 여러개의 로우를 가지되 반드시 1개의 칼럼을 가진 ndarray로 변환됨을 보장함
  + 여러 개의 넘파이 ndarray는 stack이나 concat으로 결합할 때 각각의 ndarray의 형태를 통일해 유용하게 사용됨


In [ ]:
array1=np.arange(8)
array3d=array1. reshape((2,2,2))
print('array3d:\n',array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5=array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:', array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6=array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


#5. 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱
* 단일 데이터 값 추출을 제외한 슬라이싱, 팬시 인덱싱, 불린 인덱싱으로 추출된 모든 데이터 세트는 모두 ndarray 타입

  1> 단일 값 추출
* ndarray객체에 해당하는 위치의 인덱스 값을 []안에 입력


In [ ]:
#1부터 9까지의 1차원 ndarray 생성
array1=np.arange(start=1, stop=10)
print('array1:',array1)

#인덱스는 0부터 시작하므로 array1[2]는 3번째 인덱스 위치의 데이터값을 의미
value=array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


* 인덱스에 마이너스 기호를 이용하면 맨 뒤에서부터 데이터를 추출

In [ ]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


* ndarray 내의 데이터값도 간단히 수정 가능

In [ ]:
array1[0]=9
array1[8]=0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


* 다차원 ndarray에서 단일 값 추출
  + axis 0은 로우(행) 방향의 축, axis 1은 칼럼(열) 방향의 축을 의미함
  + 넘파이 ndarray에서는 로우와 칼럽을 사용하지 않음
  + 축 기반의 연산에서 axis가 생략되면 axis 0을 의미함

In [ ]:
#1차원 ndarray를 2차원의 3X3으로 변환
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

#[row.col]을 이용해 2차원 ndarray에서 데이터 추출
print('(row=o,col=0) index 가리키는 값:', array2d[0,0])
print('(row=o,col=1) index 가리키는 값:', array2d[0,1])
print('(row=1,col=0) index 가리키는 값:', array2d[1,0])
print('(row=2,col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=o,col=0) index 가리키는 값: 1
(row=o,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


  2> 슬라이싱
* : 사이에 시작 인덱스와 종료 인덱스를 표시하면 '시작 인덱스~종료 인덱스-1'에 있는 데이터 ndarray를 반환




In [ ]:
array1=np.arange(start=1, stop=10)
array3=array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


* : 사이의 시작, 종료 인덱스는 생략 가능
  

In [ ]:
# : 앞에 시작 인덱스를 생략하면 자동으로 맨 처음 인덱스인 0으로 간주
array1 = np.arange(start=1, stop=10)
array4=array1[:3]
print(array4)

# : 뒤에 종료 인덱스를 생략하면 자동으로 맨 마지막 인덱스로 간주
array5=array1[3:]
print(array5)

# : 기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/마지막 인덱스로 간주
array6=array1[:]
print(array6)


[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


* 2차원 ndarray에서 슬라이싱: 콤마로 로우와 칼럼 인덱스를 지칭하는 부분만 다름



In [ ]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2,0:2]\n',array2d[0:2,0:2])
print('array2d[1:3,0:3]\n',array2d[1:3,0:3])
print('array2d[1:3,:]\n',array2d[1:3,:])
print('array2d[:,:]\n',array2d[:,:])
print('array2d[:2,1:]\n',array2d[:2,1:])

# 로우나 컬럼 축 한쪽에만 슬라이싱을 적용하고, 다른 쪽 축에는 단일 값 인덱스를 적용해도 됨
print('array2d[:2,0]\n',array2d[:2,0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2]
 [[1 2]
 [4 5]]
array2d[1:3,0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:]
 [[4 5 6]
 [7 8 9]]
array2d[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:]
 [[2 3]
 [5 6]]
array2d[:2,0]
 [1 4]


* 2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray를 반환함
* 3차원 ndarray에서 뒤에 오는 인덱스를 없애면 2차원 ndarray를 반환함

In [ ]:
# 로우 축(axis 0)의 첫 번째 로우 ndarray(1차원)를 반환함
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:',array2d[0].shape, 'array2d[1] shape:',array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


  3> 팬시 인덱싱: 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치에 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식

In [ ]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)

# (0.2),(1,2) 인덱싱 적용
array3=array2d[[0,1],2]
print('array2d[[0,1],2]=>', array3.tolist())

# ((0,0),(0,1)),((1,0),(1,1)) 인덱싱 적용
array4=array2d[[0,1],0:2]
print('array2d[[0,1],0:2]=>', array4.tolist())

# ((0,:),(1,:)) 인덱싱 적용
array5=array2d[[0,1]]
print('array2d[[0,1]]=>', array5.tolist())

array2d[[0,1],2]=> [3, 6]
array2d[[0,1],0:2]=> [[1, 2], [4, 5]]
array2d[[0,1]]=> [[1, 2, 3], [4, 5, 6]]


4> 불린 인덱싱
* 조건 필터링과 검색을 동시에 할 수 있기 때문에 매우 자주 사용됨
* ndarray의 인덱스를 지정하는 []내에 조건문을 그대로 기재

In [ ]:
array1d=np.arange(start=1, stop=10)

# [] 안에 array1d > 5 불린 인덱싱을 적용
array3=array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과 값:', array3)

array1d>5 불린 인덱싱 결과 값: [6 7 8 9]


* 조건으로 반환된 ndarray 객체를 인덱싱을 지정하는 [] 내에 입력하면 false 값은 무시하고 true 값이 있는 위치 인덱스 값으로 자동 변환해 해당하는 인덱스 위치의 데이터만 반환함

In [ ]:
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

* 불린 ndarray를 만들고 이를 array1d[] 내에 입력하면 동일한 데이터세트가 반환됨

In [ ]:
boolean_indexes=np.array([False,False,False,False,False,True,True,True,True])
array3=array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:',array3)

불린 인덱스로 필터링 결과: [6 7 8 9]


In [ ]:
indexes=np.array([5,6,7,8])
array4=array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


* 불린 인덱싱이 동작하는 단계
  + step 1: array1d > 5와 같이 ndarray의 필터링 조건을 []안에 기재
  + step 2: False 값은 무시하고 True 값에 해당하는 인덱스값만 저장(True값 자체인 1을 저장하는 것이 아니라 True값을 가진 인덱스를 저장함)
  + step 3: 저장된 인덱스 데이터 세트로 ndarray 조회

#6. 행렬의 정렬 - sort()와 argsort()
1> 행렬 정렬
* np.sort(): 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환함
* ndarray.sort(): 원 행렬 자체를 정렬한 형태로 변환하며 반환 값은 None임

In [53]:
org_array=np.array([3,1,9,5])
print('원본 행렬:',org_array)

# np.sort()로 정렬
sort_array1=np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)

# ndarray.sort()로 정렬
sort_array2=org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:',sort_array2)
print('org_array.sort() 호출 후 원본 행렬:',org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


* 기본적으로 오름차순이나 내림차순으로 정렬하기 위해서는 [::-1]을 적용함

In [56]:
sort_array1_desc=np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


* 행렬이 2차원 이상일 경우 axis 축 값 설정을 통해 로우(열) 방향, 또는 칼럼(행) 방향으로 정렬을 수행할 수 있음

In [57]:
array2d=np.array([[8,12],[7,1]])
sort_array2d_axis0=np.sort(array2d,axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)
sort_array2d_axis1=np.sort(array2d,axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


2>정렬된 행렬의 인덱스를 반환하기: np.argsort()를 이용하여 정렬 행렬의 원본 행렬 인덱스를 ndarray형으로 반환함

In [58]:
org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:',sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


* 기본적으로 오름차순이나 내림차순으로 정렬하기 위해서는 [::-1]을 적용함

In [60]:
org_array=np.array([3,1,9,5])
sort_indices_desc=np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:',sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


* 넘파이의 ndarray는 메타 데이터를 가질 수 없으므로 실제 값과 그 값이 뜻하는 메타 데이터를 별도의 ndarray로 각각 가져야만 함

In [62]:
import numpy as np

name_array=np.array(['John', 'Mike', 'Sarah', 'Kate' , 'Samuel'])
score_array=np.array([78,95,84,98,88])

sort_indices_asc=np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


#7. 선형대수 연산 - 행렬 내적과 전치 행렬 구하기
1> 행렬 내적(행렬 곱): np.dot()
* 두 행렬 A와 B의 내적은 np.dot()을 이용해 계산 가능
* 왼쪽 행렬의 열의 개수와 오른쪽 행렬의 행의 개수가 동일해야 내적 연산 가능

In [63]:
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[7,8],[9,10],[11,12]])
dot_product=np.dot(A,B)
print('행렬 내적 결과:\n',dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


2> 전치 행렬: transpose()
* 원 행렬에서 행과 열 위치를 교환한 원소로 구성된 행렬

In [64]:
A=np.array([[1,2],[3,4]])
transpose_mat=np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
